//******************************************************************************
//metronome.pb
//
//This package provides the protocol buffer source code for the analog update
//message that is sent by DACC to HMI (and perhaps others) via message_q.
//
//Rev Date     By  Reason
//--- -------- --- ---------------------------------------------------------------
//001			 tdm  original
//
//*****************************************************************************

// command line to generate this file: protoc -I=. --go_out=. analog.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: analog.proto

package analog_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalogChange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Value           float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	ValueColor      string                 `protobuf:"bytes,2,opt,name=valueColor,proto3" json:"valueColor,omitempty"`
	ValueBackground string                 `protobuf:"bytes,3,opt,name=valueBackground,proto3" json:"valueBackground,omitempty"`
	StateName       string                 `protobuf:"bytes,4,opt,name=stateName,proto3" json:"stateName,omitempty"`
	StateColor      string                 `protobuf:"bytes,5,opt,name=stateColor,proto3" json:"stateColor,omitempty"`
	StateBackground string                 `protobuf:"bytes,6,opt,name=stateBackground,proto3" json:"stateBackground,omitempty"`
	UnackAlarm      string                 `protobuf:"bytes,7,opt,name=unackAlarm,proto3" json:"unackAlarm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalogChange) Reset() {
	*x = AnalogChange{}
	mi := &file_analog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalogChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalogChange) ProtoMessage() {}

func (x *AnalogChange) ProtoReflect() protoreflect.Message {
	mi := &file_analog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalogChange.ProtoReflect.Descriptor instead.
func (*AnalogChange) Descriptor() ([]byte, []int) {
	return file_analog_proto_rawDescGZIP(), []int{0}
}

func (x *AnalogChange) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AnalogChange) GetValueColor() string {
	if x != nil {
		return x.ValueColor
	}
	return ""
}

func (x *AnalogChange) GetValueBackground() string {
	if x != nil {
		return x.ValueBackground
	}
	return ""
}

func (x *AnalogChange) GetStateName() string {
	if x != nil {
		return x.StateName
	}
	return ""
}

func (x *AnalogChange) GetStateColor() string {
	if x != nil {
		return x.StateColor
	}
	return ""
}

func (x *AnalogChange) GetStateBackground() string {
	if x != nil {
		return x.StateBackground
	}
	return ""
}

func (x *AnalogChange) GetUnackAlarm() string {
	if x != nil {
		return x.UnackAlarm
	}
	return ""
}

var File_analog_proto protoreflect.FileDescriptor

var file_analog_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x61, 0x6e, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x61, 0x6e, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x62, 0x22, 0xf6, 0x01, 0x0a, 0x0c, 0x61, 0x6e,
	0x61, 0x6c, 0x6f, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x12, 0x28, 0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x6e, 0x61, 0x63, 0x6b, 0x41, 0x6c, 0x61, 0x72, 0x6d,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x6e, 0x61, 0x63, 0x6b, 0x41, 0x6c, 0x61,
	0x72, 0x6d, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_analog_proto_rawDescOnce sync.Once
	file_analog_proto_rawDescData []byte
)

func file_analog_proto_rawDescGZIP() []byte {
	file_analog_proto_rawDescOnce.Do(func() {
		file_analog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analog_proto_rawDesc), len(file_analog_proto_rawDesc)))
	})
	return file_analog_proto_rawDescData
}

var file_analog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_analog_proto_goTypes = []any{
	(*AnalogChange)(nil), // 0: analog.pb.analogChange
}
var file_analog_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analog_proto_init() }
func file_analog_proto_init() {
	if File_analog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analog_proto_rawDesc), len(file_analog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analog_proto_goTypes,
		DependencyIndexes: file_analog_proto_depIdxs,
		MessageInfos:      file_analog_proto_msgTypes,
	}.Build()
	File_analog_proto = out.File
	file_analog_proto_goTypes = nil
	file_analog_proto_depIdxs = nil
}
